wbzf/Areas/Admin/Pages/AccountManagement/AccountStatement.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using wbzf.DataAccess.Repository;
using wbzf.DataAccess.Repository.IRepository;
using wbzf.Model;
using wbzf.Utility;

namespace wbzf.Areas.Admin.Pages.AccountManagement
{
    [Authorize(Roles = $"{SD.Admin}")]
    public class AccountStatementModel : PageModel
    {
        private IUnitOfWork _unitofWork;
        public IEnumerable<SelectListItem> AccountList { get; set; }
        public TransactionHistory txnHistory { get; set; }
        public AccountStatementModel(IUnitOfWork unitOfWork)
        {
            _unitofWork = unitOfWork;
        }
       

        public void OnGet()
        {
            AccountList = getAccountlist();

        }
        private IEnumerable<SelectListItem> getAccountlist()
        {
            var list = _unitofWork.account.GetAll(u => u.is_deleted == false && u.isvisibletoPublic == true, orderby: m => m.OrderBy(a => a.Name)).Select(i => new SelectListItem()
            {
                Text = i.Name + " (Account No: " + i.Account_no + " )",
                Value = i.Id.ToString()
            });
            return list;
        }
        public async Task<IActionResult> OnPostSubmit(string txnId)
        {
            return ViewComponent("TxnHist", new { _unitofWork, txnHistId = txnId });

        }
        public IActionResult OnPostTablePopup(int pageIndex = 1, int pageSize = 10, string? sortColumn = null, string? sortDirection = null, string searchTerm = "",  DateTime? fromDate = null, DateTime? toDate = null, int? accountId = null)
        {
            // Invoke component
            var component = ViewComponent("AccountStatement", new { _unitofWork, pageIndex, pageSize, sortColumn, sortDirection, searchTerm, fromDate, toDate, accountId });
            return component;

        }

    }
}

wbzf/Areas/Admin/Pages/AccountManagement/AccountTransfer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using wbzf.DataAccess.Repository.IRepository;
using wbzf.Model;
using wbzf.Utility;

namespace wbzf.Areas.Admin.Pages.AccountManagement
{
    [Authorize(Roles = $"{SD.Admin}")]
    public class AccountTransferModel : PageModel
    {
        private IUnitOfWork _unitofWork;
        private readonly UserManager<ApplicationUser> _userManager;
        [BindProperty]
        public IEnumerable<SelectListItem> userList { get; set; }
        [BindProperty]
        public MainAc MainAc { get; set; }
        [BindProperty]
        public TransactionHistory Transactions { get; set; }
        public IEnumerable<SelectListItem> AccountList { get; set; }
        public AccountTransferModel(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitofWork = unitOfWork;
            _userManager = userManager;
            MainAc = new();
            Transactions = new();
        }
        private IEnumerable<SelectListItem> getAccountlist()
        {
            var list = _unitofWork.account.GetAll(u => u.is_deleted == false, orderby: m => m.OrderBy(a => a.Name)).Select(i => new SelectListItem()
            {
                Text = i.Name + " (Account No: " + i.Account_no + " )",
                Value = i.Id.ToString()
            });
            return list;
        }
        private async Task<IEnumerable<SelectListItem>> GetUserAsync()
        {
            var userList = await (from user in _userManager.Users
                                  select new
                                  {
                                      UserId = user.Id,
                                      FullName = user.Full_Name,
                                      user.Email,
                                      user.EmailConfirmed,
                                      user.bankAcNo,

                                  }).ToListAsync();
            var list = userList.Select(i => new SelectListItem()
            {
                Text = i.FullName + " (Account No: " + i.bankAcNo + " )",
                Value = i.UserId.ToString()
            });

            return list;
        }

        public void OnGet()
        {
            AccountList = getAccountlist();
            userList = GetUserAsync().Result;
        }
      
        public IActionResult OnPost()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string ApplicationUserId = claim.Value;

            if (Transactions.Account_Id != Transactions.ToAccount_Id)
            {
                double balance = _unitofWork.mainAccount.GetFirstOrDefault(a => a.Account_Id == Transactions.Account_Id, orderby: m => m.OrderByDescending(c => c.Created_at)).Bal;
                if (Transactions.Amount > balance)
                {
                    TempData["warning"] = "Transaction can not be proceed due to Insufficient Balance.";
                }
                else
                {
                    Transactions.Transaction_Purpose = SD.Account_Transfer;
                    Transactions.PayBy_Id = ApplicationUserId;
                    Transactions.Created_at = DateTime.UtcNow.AddHours(5).AddMinutes(30);
                    Transactions.Payment_Status = SD.Success;
                    _unitofWork.transactionHistory.Add(Transactions);
                    _unitofWork.Save();
                    _unitofWork.mainAccount.updateBalance(SD.Substract, Transactions.Id);
                    _unitofWork.Save();

                    TempData["success"] = "Account Transfer has been Successfull.";
                }
            }
            else { TempData["warning"] = "From Account and To Account can not be same."; }
            return RedirectToPage();
        }


    }


}

wbzf/Areas/Admin/Pages/AccountManagement/Deposit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using wbzf.DataAccess.Repository;
using wbzf.DataAccess.Repository.IRepository;
using wbzf.Model;
using wbzf.Utility;

namespace wbzf.Areas.Admin.Pages.AccountManagement
{
    [Authorize(Roles = $"{SD.Admin}")]
    public class DepositModel : PageModel
    {
        private IUnitOfWork _unitofWork;
        public MainAc MainAcTxn { get; set; }
        [BindProperty]
        public TransactionHistory Transactions { get; set; }
        public IEnumerable<SelectListItem> AccountList { get; set; }
        public DepositModel(IUnitOfWork unitOfWork)
        {
            MainAcTxn = new();
            Transactions = new();
            _unitofWork = unitOfWork;
        }
        private IEnumerable<SelectListItem> getAccountlist()
        {
            var list = _unitofWork.account.GetAll(u => u.is_deleted == false && u.isvisibletoPublic == true, orderby: m => m.OrderBy(a => a.Name)).Select(i => new SelectListItem()
            {
                Text = i.Name + " (Account No: " + i.Account_no + " )",
                Value = i.Id.ToString()
            });
            return list;
        }

        public void OnGet()
        {
            AccountList = getAccountlist();

        }

        public IActionResult OnPost()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string ApplicationUserId = claim.Value;
            Transactions.transaction_fees = Transactions.transaction_fees ?? 0;

            Transactions.received_amount = Transactions.Amount - Transactions.transaction_fees.Value;
            Transactions.Transaction_Purpose = SD.Deposite;
            Transactions.PayBy_Id = ApplicationUserId;
            Transactions.Created_at = DateTime.UtcNow.AddHours(5).AddMinutes(30);
            Transactions.Payment_Status = SD.Success;
            _unitofWork.transactionHistory.Add(Transactions);
            _unitofWork.Save();

            _unitofWork.mainAccount.updateBalance(SD.Add, Transactions.Id);
            _unitofWork.Save();
            TempData["success"] = "Amount has been Deposited to the Accont Successfully.";
            return RedirectToPage();
        }


    }
}

wbzf/Areas/Admin/Pages/AccountManagement/MakePayment.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Security.Claims;
using wbzf.DataAccess.Repository;
using wbzf.DataAccess.Repository.IRepository;
using wbzf.Model;
using wbzf.Model.ViewModel;
using wbzf.Utility;

namespace wbzf.Areas.Admin.Pages.AccountManagement
{
    [Authorize(Roles = $"{SD.Admin}")]
    public class MakePaymentModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private IUnitOfWork _unitofWork;
        [BindProperty]
        public IEnumerable<SelectListItem> userList { get; set; }
        [BindProperty]
        public MainAc MainAc { get; set; }
        [BindProperty]
        public TransactionHistory Transactions { get; set; }
        public IEnumerable<SelectListItem> AccountList { get; set; }
        public MakePaymentModel(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitofWork = unitOfWork;
            _userManager = userManager;
            MainAc = new();
            Transactions = new();
        }
        private IEnumerable<SelectListItem> getAccountlist()
        {
            var list = _unitofWork.account.GetAll(u => u.is_deleted == false, orderby: m => m.OrderBy(a => a.Name)).Select(i => new SelectListItem()
            {
                Text = i.Name + " (Account No: " + i.Account_no + " )",
                Value = i.Id.ToString()
            });
            return list;
        }
        
       
        private async Task<IEnumerable<SelectListItem>> GetUserAsync()
        {
            var userList = await (from user in _userManager.Users
                                  select new
                                  {
                                      UserId = user.Id,
                                      FullName = user.Full_Name,
                                      user.Email,
                                      user.EmailConfirmed,
                                      
                                  }).ToListAsync();
            var list = userList.Select(i=>new SelectListItem()
            {
                Text=i.FullName,
                Value=i.UserId.ToString()
            });
            
            return list;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            AccountList = getAccountlist();
            userList = GetUserAsync().Result;
            return Page();
        }
       
        public IActionResult OnPost()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string ApplicationUserId = claim.Value;
            double balance = _unitofWork.mainAccount.GetFirstOrDefault(a => a.Account_Id == Transactions.Account_Id, orderby: m => m.OrderByDescending(c=>c.Created_at)).Bal;
                if (Transactions.Amount > balance)
                {
                    TempData["warning"] = "Transaction can not be proceed due to Insufficient Balance.";
                }
                else
                {
                    Transactions.PayBy_Id = ApplicationUserId;
                    Transactions.Created_at = DateTime.UtcNow.AddHours(5).AddMinutes(30);
                    Transactions.Payment_Status = SD.Success;
                    _unitofWork.transactionHistory.Add(Transactions);
                    _unitofWork.Save();
                    _unitofWork.mainAccount.updateBalance(SD.Substract, Transactions.Id);
                    _unitofWork.Save();

                    TempData["success"] = "Payment success.";
                }
            return RedirectToPage();
        }

    }
}

wbzf/Areas/Admin/Pages/AccountManagement/AccountTransfer.cshtml
@page
@using wbzf.Utility;
@model wbzf.Areas.Admin.Pages.AccountManagement.AccountTransferModel
@{
    ViewData["Title"] = "Account Transfer";
}
<div class="row">
    <div class="col-xs-12">
        <div class="page-title-box">
            <h4 class="page-title"> @ViewData["Title"] </h4>
            <ol class="breadcrumb p-0 m-0">
                <li>
                    <a asp-area="Admin" asp-page="/dashboard">Home</a>
                </li>

                <li class="active">
                    @ViewData["Title"]
                </li>

            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<form method="post">
    <div class="col-md-6">
        <div class="panel panel-color panel-primary">

            <div class="panel-heading">
                <h3 class="panel-title">
                    Money Transfer To Another Account
                </h3>
            </div>
            <div class="panel-body">

                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="@Model.Transactions.Accounts.Name">From Account Name <span class="text-danger">*</span></label>

                        <select id="fromAccount_Id" asp-for="@Model.Transactions.Account_Id" asp-items="@Model.AccountList" class="required form-control">
                            <option disabled selected>--Please Select Account--</option>
                        </select>
                        <span asp-validation-for="@Model.Transactions.Account_Id" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-lg-12">
                            <label>Account Type<span class="text-danger"> *</span></label>
                        </div>
                        <div class="col-lg-6">
                            <div class="radio">
                                <input type="radio" required  name="rdTxnMode" value="ownAccount" id="ownAccount" />
                                <label>Own Funds</label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="radio">
                                <input type="radio" required name="rdTxnMode" value="otherAccount" id="otherAccount" />
                                <label>Other Account</label>
                            </div>
                        </div>
                    </div>
                </div>
            
                <div id="ownAccountDetails">
                   <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="@Model.Transactions.ToAccounts.Name">To Account Name <span class="text-danger">*</span></label>

                        <select id="toAccount_Id" asp-for="@Model.Transactions.ToAccount_Id" asp-items="@Model.AccountList" class="required form-control">
                            <option disabled selected>--Please Select Account--</option>
                        </select>
                        <span asp-validation-for="@Model.Transactions.ToAccount_Id" class="text-danger"></span>
                    </div>
                </div>
                </div>
                <div id="otherAccountDetails">
                   <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="@Model.Transactions.PayTo_Id">To Account Name <span class="text-danger">*</span></label>

                            <select asp-for="@Model.Transactions.PayTo_Id" asp-items="@Model.userList" class="required form-control">
                            <option disabled selected>--Please Select Account--</option>
                        </select>
                            <span asp-validation-for="@Model.Transactions.PayTo_Id" class="text-danger"></span>
                    </div>
                </div>
                </div>
                
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Amount <span class="text-danger">*</span></label>
                        <input type="number" min="0" asp-for="@Model.Transactions.Amount" class="required form-control" placeholder="Enter Amount" />
                        <span asp-validation-for="@Model.Transactions.Amount" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="@Model.Transactions.transaction_fees">Transaction Charges </label>
                        <input type="number" min="0" asp-for="@Model.Transactions.transaction_fees" class="form-control" placeholder="Enter Transaction Charges" />
                        <span asp-validation-for="@Model.Transactions.transaction_fees" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">

                        <label asp-for="@Model.Transactions.Remarks">Remarks </label>
                        <input type="text" asp-for="@Model.Transactions.Remarks" class="form-control" placeholder="Enter Remarks" />
                        <span asp-validation-for="@Model.Transactions.Remarks" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-block btn-md btn-success" asp-page-handler="Submit" style="font-size:medium">Save </button>

                </div>

            </div>
        </div>
    </div>
    </div>
</form>
@section scripts {
    <script>
        $(document).ready(function () {
            // Hide both sections on page load
            $('#ownAccountDetails').hide();
            $('#otherAccountDetails').hide();

            // Show/hide sections based on the selected radio button
            $('input[name="rdTxnMode"]').change(function () {
                if ($(this).val() == 'ownAccount') {
                    $('#ownAccountDetails').show();
                    $('#otherAccountDetails').hide();
                } else if ($(this).val() == 'otherAccount') {
                    $('#ownAccountDetails').hide();
                    $('#otherAccountDetails').show();
                }
            });
        });
    </script>
    <script src="~/js/accountTransaction.js" asp-append-version="true"></script>

    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_Notification" />
    }

}

wbzf/Areas/Admin/Pages/AccountManagement/Deposit.cshtml
@page
@using wbzf.Utility;
@model wbzf.Areas.Admin.Pages.AccountManagement.DepositModel
@{
    ViewData["Title"] = "Deposit";
}
<div class="row">
    <div class="col-xs-12">
        <div class="page-title-box">
            <h4 class="page-title"> @ViewData["Title"] </h4>
            <ol class="breadcrumb p-0 m-0">
                <li>
                    <a asp-area="Admin" asp-page="/dashboard">Home</a>
                </li>

                <li class="active">
                    @ViewData["Title"]
                </li>

            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<form method="post">
    <div class="col-md-6">
        <div class="panel panel-color panel-teal">

            <div class="panel-heading">
                <h3 class="panel-title">
                    Deposite Money To Account
                </h3>
            </div>


            <div class="panel-body">

                <div class="form-group">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Account <span class="text-danger">*</span></label>

                            <select  asp-for="@Model.Transactions.Account_Id" asp-items="@Model.AccountList" class="required form-control">
                                <option disabled selected>--Please Select Account--</option>
                            </select>
                            <span asp-validation-for="@Model.Transactions.Accounts.Name" class="text-danger"></span>
                        </div>
                    </div>
                   
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Amount <span class="text-danger">*</span></label>
                            <input type="number" min="0" asp-for="@Model.Transactions.Amount" class="required form-control" placeholder="Enter Amount" />
                            <span asp-validation-for="@Model.Transactions.Amount" class="text-danger"></span>
                        </div>
                    </div>
                     <div  class="col-md-12">
                        <div class="form-group">

                            <label asp-for="@Model.Transactions.transaction_fees">Transaction Charges </label>
                            <input type="number" min="0" asp-for="@Model.Transactions.transaction_fees" class="form-control" placeholder="Enter Transaction Charges" />
                            <span asp-validation-for="@Model.Transactions.transaction_fees" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">

                            <label asp-for="@Model.Transactions.Remarks">Remarks </label>
                            <input type="text" asp-for="@Model.Transactions.Remarks" class="form-control" placeholder="Enter Remarks" />
                            <span asp-validation-for="@Model.Transactions.Remarks" class="text-danger"></span>
                        </div>
                    </div>
                    <br/>
                    <div class="col-md-6 pull-right">
                        <button type="submit" class="btn btn-block btn-md btn-success" asp-page-handler="Submit" style="font-size:medium">Save </button>

                    </div>
                </div>

            </div>

        </div>


    </div>
</form>


@section scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var transactionChargesDiv = document.getElementById('transaction_charges');
            var txnFees = document.getElementById('txnFees');
            var noTxnFees = document.getElementById('noTxnFees');

            function toggleTransactionCharges() {
                if (txnFees.checked) {
                    transactionChargesDiv.style.display = 'block';
                } else {
                    transactionChargesDiv.style.display = 'none';
                }
            }

            noTxnFees.addEventListener('change', toggleTransactionCharges);
            txnFees.addEventListener('change', toggleTransactionCharges);

            // Initial check to set visibility on page load
            toggleTransactionCharges();
        });
    </script>

    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_Notification" />
    }

}

wbzf/Areas/Admin/Pages/AccountManagement/MakePayment.cshtml
@page
@using wbzf.Utility;
@model wbzf.Areas.Admin.Pages.AccountManagement.MakePaymentModel
@{
    ViewData["Title"] = "Make Payment";
}
<div class="row">
    <div class="col-xs-12">
        <div class="page-title-box">
            <h4 class="page-title"> @ViewData["Title"] </h4>
            <ol class="breadcrumb p-0 m-0">
                <li>
                    <a asp-area="Admin" asp-page="/dashboard">Home</a>
                </li>

                <li class="active">
                    @ViewData["Title"]
                </li>

            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<form method="post">
    <div class="col-md-6">
        <div class="panel panel-color panel-teal">

            <div class="panel-heading">
                <h3 class="panel-title">
                    Make Payment
                </h3>
            </div>


            <div class="panel-body">

                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="@Model.Transactions.Accounts.Name">Account Name <span class="text-danger">*</span></label>

                        <select id="account_Id" asp-for="@Model.Transactions.Account_Id" asp-items="@Model.AccountList" class="required form-control">
                            <option disabled selected>--Please Select Account--</option>
                        </select>
                        <span asp-validation-for="@Model.Transactions.Accounts.Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label>Payment Purpose <span class="text-danger">*</span></label>

                        <select id="payment_PurposeId" asp-for="@Model.Transactions.Transaction_Purpose" class="required form-control">
                            <option disabled selected>--Please Select Payment Purpose--</option>
                            <option value="@SD.Expence"> @SD.Expence</option>
                            <option value="@SD.Salary"> @SD.Salary</option>

                        </select>
                        <span asp-validation-for="@Model.Transactions.Transaction_Purpose" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-lg-12">
                            <label>Pay To<span class="text-danger"> *</span></label>
                        </div>
                        <div class="col-lg-6">
                            <div class="radio">
                                <input type="radio" required checked name="rdTxnMode" value="registered" id="registered" />
                                <label>Registered Member</label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="radio">
                                <input type="radio" required name="rdTxnMode" value="unregistered" id="unregistered" />
                                <label>Un-Registered Member</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="payTo_Id" class="col-md-12">
                    <div class="form-group">
                        <select asp-for="@Model.Transactions.PayTo_Id" asp-items="@Model.userList" class="required form-control">
                            <option disabled selected>--Please Select Member--</option>
                        </select>
                        <span asp-validation-for="@Model.Transactions.PayTo_Id" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Amount <span class="text-danger">*</span></label>
                        <input type="number" min="0" asp-for="@Model.Transactions.Amount" class="required form-control" placeholder="Enter Amount" />
                        <span asp-validation-for="@Model.Transactions.Amount" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="@Model.Transactions.transaction_fees">Transaction Charges </label>
                        <input type="number" min="0" asp-for="@Model.Transactions.transaction_fees" class="form-control" placeholder="Enter Transaction Charges" />
                        <span asp-validation-for="@Model.Transactions.transaction_fees" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">

                        <label asp-for="@Model.Transactions.Remarks">Remarks </label>
                        <input type="text" asp-for="@Model.Transactions.Remarks" class="form-control" placeholder="Enter Remarks" />
                        <span asp-validation-for="@Model.Transactions.Remarks" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6 pull-right">
                    <button type="submit" class="btn btn-block btn-md btn-success" asp-page-handler="Submit" style="font-size:medium">Save </button>

                </div>
            </div>

        </div>


    </div>
</form>


@section scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var transactionChargesDiv = document.getElementById('payTo_Id');
            var registered = document.getElementById('registered');
            var unregistered = document.getElementById('unregistered');

            function toggleTransactionCharges() {
                if (registered.checked) {
                    transactionChargesDiv.style.display = 'block';
                } else {
                    transactionChargesDiv.style.display = 'none';
                }
            }

            unregistered.addEventListener('change', toggleTransactionCharges);
            registered.addEventListener('change', toggleTransactionCharges);

            // Initial check to set visibility on page load
            toggleTransactionCharges();
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_Notification" />
    }

}